### ISSUE TITLE
Crear WordPress de Día 256

### ISSUE THREAD

**Issue by JFerT** [FranciscoMartinez33/proyectoFS#107]
Crear sitio funcional en hosting remoto de Sitio Institucional en WordPress (Este punto es para presentar al Empresa Ficticia que el grupo conforma, por lo que es parte indirecta del Proyecto. Pueden crear una sección en la Wiki con los registros de este sitio).

**Comment by CintiaOsorioDuartesakura** [comment]
Se asigno a @danielasch00 @evera8 @CintiaOsorioDuartesakura para esta tarea.

**Comment by CintiaOsorioDuartesakura** [comment]
Hare un apartado con el link para que todos podamos entrar al link al wordpress.
