### ISSUE TITLE
Definir nombre de la empresa del cliente (Documento con 10 nombres fantasía)

### ISSUE THREAD

**Issue by Gaghyta** [FranciscoMartinez33/proyectoFS#3]

**Comment by Gaghyta** [comment]
**_LISTA DE NOMBRES POSIBLES PARA LA EMPRESA DE INDUMENTARIA VIRTUAL_**

1. VirtualTrend (Carla Antonini)
2. 3D-Models (Carla Antonini)
3. Virtual3DTribute Brand (Vera Emilio A.)
4. Virtual clothing company (Ricardo)
5. Cool look / Kool looK (Fernando)
6. Puntadas-diseño de ropa 3d (Cintia Osorio Duarte)
7. Dream clothes (Cintia Osorio Duarte)
8. Fashionart3D (Yamila Cáceres)
9. Confeccióndigital (Francisco Martinez)
10. Yourclothing3D (Martiniano Lurgo)

**Comment by Gaghyta** [comment]
Agregar nombres posibles y adjuntar nombre del que propone

**Comment by ricardoeapfelbaum** [comment]
virtual clothing company(Ricardo)

**Comment by JFerT** [comment]
Hay también una Wiki para poner los posibles nombres de la empresa del cliente. Habría que unificar todo.

**Comment by CintiaOsorioDuartesakura** [comment]
Agregue a la lista mi segunda propuesta de nombre de la empresa del cliente.

**Comment by Yamiibel** [comment]
Nombre posible agregado

**Comment by MartinianoLurgo** [comment]
Agregue otro nombre posible: Yourclothing3D (Martiniano Lurgo)

**Comment by JFerT** [comment]
Por votación cerrada el 13/10 se eligió el nombre VirtualTrend
