### ISSUE TITLE
Definir nombre de nuestra empresa de desarrollo.

### ISSUE THREAD

**Issue by Gaghyta** [FranciscoMartinez33/proyectoFS#4]

**Comment by ricardoeapfelbaum** [comment]
Ya se encuentra a disposicion en la wiki una pagina para proponer nombres!

**Comment by CintiaOsorioDuartesakura** [comment]
Realice la wiki con mi propuesta de nombre de la pagina y de la empresa.

**Comment by evera8** [comment]
Agregue en Wiki idea de nombre

**Comment by JFerT** [comment]
[Link directo a la Wiki correspondiente](https://github.com/FranciscoMartinez33/proyectoFS/wiki/Nombres-para-nuestra-empresa-de-desarrollo-de-software)

**Comment by JFerT** [comment]
@evera8 vi que pusiste "3dclothes" en la wiki de los nombres para nuestra empresa de desarrollo de software, ojo esto es aparte de la empresa de ropa.
