### ISSUE TITLE
Tarea por integrante para el armado de base de datos usuarios

### ISSUE THREAD

**Issue by evera8** [FranciscoMartinez33/proyectoFS#71]
Inventamos 5 usuarios con estos datos para Base de datos con estos campos:

nombre
apellido
provincia (Argentina)
ciudad 5)dirección (formato de calle y número)
codigo postal
teléfono
documento nacional de identidad

**Comment by CintiaOsorioDuartesakura** [comment]
Aca agrego 10 nombres-

Nombres	Apellidos	DNI	Domicilio	Codigo Postal	Ciudad	Provincia	Telefono 	Email
Jose 	Fernandez	32450226	Paso 235	1428	Capital Federal	Buenos Aires	1532049623	JosFer@yaya.com
Maria 	Iriarte	20222412	Las flores 12	2645	Concordia	Entre Rios	3431164531	Maria.Iriarte@gmail.com
Rogelio 	Paredes	12343256	Corralon 2424	4848	Posadas	Misiones	3764465740	r.p46@yahoo.com.ar
Victoria 	Yplanes	25111523	Aviadores 23	1628	Beccard	Buenos Aires	1524875647	Victoria.Yplanes@hotmail.com
Armando 	Rejas	35231987	Piedras 2828	450	Santa Fe	Santa Fe	3424441543	A.Rejas@gmail.com
Lucia 	Fernandez	27658586	Posadas 1782	1544	Moreno	Buenos Aires	1546352178	LuciFer@gmail.com
Martin	Oviedo	32478653	fleming 222	1248	Banfield	Buenos Aires	1534628887	M.Oviedo@yahoo.com
Carolina	Hernandez	27436123	Cucha Cucha 2371	1142	San Miguel	Buenos Aires	1523334421	Carohernandez@gmail.com
Javier 	Avalos	20735987	Rio negro 2147	1378	Capital Federal	Buenos Aires	1579861263	AvalosJavier@gmail.com
Adam	Wood	92410561	Cuntanilla 248	1148	El Palomar	Buenos Aires	1541110666	wood23@yahoo.com

**Comment by evera8** [comment]
Aca agrego 5 nombres-

Nombres Apellidos DNI Domicilio Codigo Postal Ciudad Provincia Telefono Email

Adnres Gonzales 25878657 Av Marcelo t. de alvear 855 5000  Córdoba Cordoba11c 3513370557 [AndyFernandez@yaya.com](mailto:AndyFernandez@yaya.com)

Pablo Vera 316464323 Av. Tosco 3235 5000 5014 Cordoba Cordoba 3513370994[Pabloavera@gmail.com](mailto:Pabloavera@gmail.com)

Valeria Givaudant 29429448  Forestieri 4848 5016  Cordoba Cordoba 35133605098 [valegivaudant@yahoo.com.ar](mailto:valegivaudant@yahoo.com.ar)

Marta Zayas 10110222 Aviador Locatelli 34 5034 Cordoba Cordoba 1524875647 [martazay@hotmail.com](mailto:martazay@hotmail.com)

Gustavo Vega 3513350678 palamara 2828 5014 Cordoba Cordoba 351567890 [gusvega12@gmail.com](mailto:gusvega12@gmail.com)

**Comment by Gaghyta** [comment]
5 USUARIOS (Están subidos a la carpeta correspondiente a BD)

1) Jorge Francisco,  Márquez, Buenos Aires, Ciudad Autónoma de Buenos Aires, Paso 56, C1031ABB, 01149511339, 26.067.345

email: jorgemarquez@hotmail.com



2) Ivana Soledad, Avalos, Catamarca, San Fernando del Valle de Catamarca, De La Quintana 147, K4700, 03834231009, 26.365.617 

email: ivita_avalos@gmail.com


3) Mariel, Montalbam, Jujuy, San Salvador de Jujuy,Gral. Lavalle 546, Y4600EAL, 03884222447,26.731.564


email: marita_montalbam@hotmail.com



4) Andres Ricardo, Bravo, San Juan, Concepción, Marqués de Aguado 373,J5400CAE, 02644212020,30.892.662

email: andre_bravo@gmail.com


5) Jorge Horacio,Cassini, La Pampa, Gral. Pico, Av. San Martín 377, L6360, 02302334033,4.559.455 

email: horaciocassini_12@hotmail.com

**Comment by Gaghyta** [comment]
OTROS 5 USUARIOS (Están subidos a la carpeta correspondiente a BD)

6) Marcelo Ruben, Gazarrosian, Chubut, Puerto Madryn, Bolívar 100, U9120, 02804000233,23.944.667

email: marcelo_gaza@hotmail.com


7) Rita Alejandra, Bevilacqua, Santa Cruz,Río Gallegos, Avellaneda 297,Z9400, 02966346736,16.531.692

email: aleale1964@gmail.com

8) Cecilia Irene, Sokolow, Corrientes, Mercedes, España 1165, W3470, 03773420754,25.089.048

email: sokolow_ire@hotmail.com


9) Sofia Bianca, Fiszner, Entre Rios, Villaguay, Necochea 461,E3240EWI, 03455420298,40.642.774

email: sofibianc1020@hotmail.com


10) Francisca Emilia, Raffo, Santa Fé, Ciudad de Santa Fé, Pje. Ingenieros 7251,S3004LDI,03424691616,16883593

email: franchemi@gmail.com

**Comment by ProgramadorPegasus** [comment]
Nombre y Apellido / Provincia (AR) / Ciudad/ Dirección / CP / Teléfono / DNI

JAVIER RODOLFO CATALAN/ RIO NEGRO / GUARDIA 133 / CIPOLLETTI / 8324 / 155728061 / 29354895
JOSE CARLOS ALFONSO / RIO NEGRO / CHIPAUQUIL / ROSAS 100 / 8536 / 1547812877 / 29888555
JORGE LEANDRO CASTRO / RIO NEGRO / NAUPA HUEN / CATRIEL 44 / 8313 / 1558898654 / 30462599
JUAN PEDRO ALDOSIVI / RIO NEGRO / EL CUY / MANSO 66 / 8333 / 1562875642 / 33645285
LEANDRO FRANCISCO JARA / RIO NEGRO / GENERAL CONESA / RIO 333 / 8503 / 1587826542 / 35999653
