### ISSUE TITLE
Abrir documento para mapear el sitio 

### ISSUE THREAD

**Issue by Gaghyta** [FranciscoMartinez33/proyectoFS#9]
Les doy acceso a todos ( @FranciscoMartinez33  @CintiaOsorioDuartesakura @CintiaOsorioDuartesakura  @Yamiibel  @evera8  y a los que aún no están en el repo y la wiki) a este doc: [https://drive.google.com/file/d/1MCduWZP-pEyRdZrSoPcZXdvfA_3TTKxp/view?usp=sharing](https://drive.google.com/file/d/1MCduWZP-pEyRdZrSoPcZXdvfA_3TTKxp/view?usp=sharing) por si quieren ir chusmeando esta herramienta que se usa para muchas cosas en programación. 

Se pueden hacer modelados de entidades y relaciones (sea para Bases de Datos -relacionar tablas- o para hacer los llamados "objetos" de los lenguajes que usan el llamado "paradigmas orientado a objetos") También se pueden hacer mapas de todo tipo (como los de sitio) y diagramas de flujo.
Adjunté una página a la wiki con un tutorial (hay muchos) en el que usan esta herramienta para trabajar el mapa del sitio. Estaría bueno poder armarlo en una herramienta de este tipo que permite trabajar online y compartir el docu

**Comment by Gaghyta** [comment]
E-mails enviados  por la función de compartir a las casillas colocadas en el formulario que completamos al inicio.

**Comment by evera8** [comment]
Perfecto carla recibido ahora lo veo

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Carla ***@***.***>
Enviado: miércoles, 21 de septiembre de 2022 22:32
Para: ***@***.***>
CC: Emilio A. ***@***.***>; ***@***.***>
Asunto: [FranciscoMartinez33/proyectoFS] Abrir documento para mapear el sitio y dar acceso (Issue #9)


Les doy acceso a todos ( @FranciscoMartinez33<https://github.com/FranciscoMartinez33> @CintiaOsorioDuartesakura<https://github.com/CintiaOsorioDuartesakura> @CintiaOsorioDuartesakura<https://github.com/CintiaOsorioDuartesakura> @Yamiibel<https://github.com/Yamiibel> @evera8<https://github.com/evera8> y a los que aún no están en el repo y la wiki) a este doc: https://drive.google.com/file/d/1MCduWZP-pEyRdZrSoPcZXdvfA_3TTKxp/view?usp=sharing por si quieren ir chusmeando esta herramienta que se usa para muchas cosas en programación.

Se pueden hacer modelados de entidades y relaciones (sea para Bases de Datos -relacionar tablas- o para hacer los llamados "objetos" de los lenguajes que usan el llamado "paradigmas orientado a objetos") También se pueden hacer mapas de todo tipo (como los de sitio) y diagramas de flujo.
Adjunté una página a la wiki con un tutorial (hay muchos) en el que usan esta herramienta para trabajar el mapa del sitio. Estaría bueno poder armarlo en una herramienta de este tipo que permite trabajar online y compartir el docu

**Comment by CintiaOsorioDuartesakura** [comment]
Buenísimo Carla iré viendolo.
